### PR TITLE
Assorted menu fixes 

### PR DESCRIPTION
**Pull request by marmarta**
- fix child dispvm icon
- make favorites the default page
- workaround for pageup bug
- launch first search result on enter 
- use keywords in search
- fix favorites in search
- fix and update tests, make them run in CI

fixes https://github.com/QubesOS/qubes-issues/issues/9009
references https://github.com/QubesOS/qubes-issues/issues/8043
fixes https://github.com/QubesOS/qubes-issues/issues/9008
fixes https://github.com/QubesOS/qubes-issues/issues/8662
fixes https://github.com/QubesOS/qubes-issues/issues/8826
fixes https://github.com/QubesOS/qubes-issues/issues/8400
fixes https://github.com/QubesOS/qubes-issues/issues/9021

### CODE REVIEW

**Comment by marmarta** [comment]
PipelineRetry

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarta** [comment]
PipelineRetry

**Comment by marmarek** [comment]
Favorites always as a default tab may not be a good idea for users not wanting to use this feature. While I like it myself (as I do use favorites), it's an extra click for many other users. Please move this one change to a separate PR (together with making it configurable).

**Comment by marmarek** [comment]
> launch first search result on enter

This works, but the item is not highlighted, so it isn't easy to see what will happen (only "Any qube" is highlighted). IIUC the reason to not highlight the item directly is to avoid space also launching the item during search, but maybe we can disable launching with space globally in the menu (so, only enter launches)?

**Comment by marmarta** [comment]
Sooo, I pushed a variant on that, but I'd love some testing if it's convenient to use. Now:
- space never launches an app
- first result should be highlighted in search results

**Review by marmarek — APPROVED** [review]

**Pull request merged**
