### PR TITLE
Make the menu into a systemctl service

### PR DESCRIPTION
**Pull request by marmarta**
Also, make it dbus-activeable, so it starts by itself in the background when needed.

### CODE REVIEW

**Comment by marmarta** [comment]
PipelineRetryFailed

**Comment by marmarta** [comment]
I'm trying to make it into an activable dbus service, please don't merge before.

**Review by marmarek — CHANGES_REQUESTED** [review]
When the button is clicked the first time (so the service gets activated via dbus), the menu only quickly flashes. I guess that's because when service is started, the menu is shown, but then it handles dbus message about the click, so it hides itself.

Maybe service needs `--background`?

**Comment by marmarta** [comment]
That's actually something of a problem... I don't want to show the menu on system boot (because it's silly), but I want to show it on first activation if it wasn't running before due to some error. Not sure how to fix this, tbh.

**Pull request merged**
